<%=chart :polar %>

  <%=component :draw %>   
    components:         
      - <%=drawing :text %>
        color:    '000033'
        alpha:    25
        rotation: 0
        bold:     true
        size:     30
        x:        0
        y:        0
        width:    390
        height:   295
        h_align:  right
        v_align:  bottom
        text:     Wind Speed
    - <%=drawing :circle %>
        layer:    background
        radius:   170
        fill_alpha: 0
        line_color: '000000'
        line_alpha: 5
        line_thickness: 40
        x:        155
        y:        140

  <%=component :axis_category %>
    size: 12
    alpha: 25
    orientation: circular
    color: '000000'

  <%=component :axis_ticks %>
    value_ticks: 1
    minor_count: 0
    major_color: 444444
    major_thickness: 2
    category_ticks: 1

  <%=component :axis_value %>
    background_color: 446688
    size: 11
    alpha: 90
    max: 60
    color: ffffff
    show_min: 

  <%=component :chart_border %>
    bottom_thickness: 2
    left_thickness: 2
    color: 444444

  <%=component :chart_grid_h %>
    alpha: 20
    thickness: 1
    type: solid
    color: 000000

  <%=component :chart_grid_v %>
    alpha: 10
    thickness: 2
    type: dotted
    color: 000000

  <%=component :chart_pref %>
    type: line
    point_size: 0
    fill_shape: 
    point_shape: none
    line_thickness: 2
    grid: circular

  <%=component :chart_rect %>
    x: -20
    positive_alpha: 10
    y: 40
    height: 200
    positive_color: 000000
    width: 350

  <%=component :legend_label %>
    size: 12
    alpha: 90
    bullet: line
    color: ffffff
    layout: vertical

  <%=component :legend_rect %>
    x: 290
    fill_alpha: 10
    y: 180
    margin: 5
    height: 70
    width: 20

  <%=component :series_color %>
    colors: ff4400,ffff00,88ffff,88ff00